version: '3.8'

services:
  site:
    build: .
    container_name: site-service
    restart: always
    networks:
      - juvantia-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site.rule=Host(`juvantia.org`) || Host(`www.juvantia.org`)"
      - "traefik.http.routers.site.entrypoints=websecure"
      - "traefik.http.routers.site.tls.certresolver=myresolver"
      - "traefik.http.services.site.loadbalancer.server.port=80"

networks:
  juvantia-network:
    external: true
